client:
  server-url: http://ec2-54-95-61-230.ap-northeast-1.compute.amazonaws.com:8080
  sync-dir: ${CLIENT_SYNC_DIR:./local}
  compress-strategy: ${CLIENT_COMPRESS_STRATEGY:zip}
  enable-auto-sync: ${CLIENT_ENABLE_AUTO_SYNC:true}
  email: ${CLIENT_EMAIL:2120320012@qq.com} # 改成自己的
  password: ${CLIENT_PASSWORD:123456} # 改成自己的

spring:
  main:
    allow-bean-definition-overriding: true